---
slug: elixir-book
filename: elixir-book
title: Elixir
subtitle: Getting Started
description: elixir-lang / elixir-lang.github.com
author: 64 contributors
copyright: 2014
uuid: c81665d8-a1e5-429e-9019-63f09a4cc41a
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
